from enum import StrEnum


class EvidenceClass(StrEnum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    INFERRED = "INFERRED"
    HYPOTHESIS = "HYPOTHESIS"
    DISPUTED = "DISPUTED"
    UNKNOWN = "UNKNOWN"
    SUPERSEDED = "SUPERSEDED"


class ControlMode(StrEnum):
    ENDOGENOUS = "ENDOGENOUS"
    EXOGENOUS_TRAJECTORY = "EXOGENOUS_TRAJECTORY"
    INTERVENTION_CONTROLLED = "INTERVENTION_CONTROLLED"
    ABSENT = "ABSENT"


class StructuralResultLabel(StrEnum):
    ROBUST_ACROSS_FAMILIES = "ROBUST_ACROSS_FAMILIES"
    FAMILY_SENSITIVE = "FAMILY_SENSITIVE"
    IDENTIFICATION_LIMITED = "IDENTIFICATION_LIMITED"
    CONTROL_ONLY = "CONTROL_ONLY"
    UNKNOWN = "UNKNOWN"


class BenchmarkResultLabel(StrEnum):
    OUTPERFORMS_B0_ON_DECLARED_HOLDOUT = "OUTPERFORMS_B0_ON_DECLARED_HOLDOUT"
    OUTPERFORMS_B1_ON_DECLARED_HOLDOUT = "OUTPERFORMS_B1_ON_DECLARED_HOLDOUT"
    NO_PREDICTIVE_GAIN_OVER_BENCHMARK = "NO_PREDICTIVE_GAIN_OVER_BENCHMARK"
    BENCHMARK_SUPERIOR_ON_HISTORICAL_HOLDOUT = "BENCHMARK_SUPERIOR_ON_HISTORICAL_HOLDOUT"
    INTERVENTION_COMPARISON_NOT_APPLICABLE_TO_BENCHMARK = (
        "INTERVENTION_COMPARISON_NOT_APPLICABLE_TO_BENCHMARK"
    )


class IdentifiabilityClass(StrEnum):
    IDENTIFIABLE_ENOUGH_FOR_TEST = "IDENTIFIABLE_ENOUGH_FOR_TEST"
    WEAKLY_IDENTIFIABLE = "WEAKLY_IDENTIFIABLE"
    UNIDENTIFIABLE_WITH_CURRENT_EVIDENCE = "UNIDENTIFIABLE_WITH_CURRENT_EVIDENCE"
    OBSERVATION_MODEL_INADEQUATE = "OBSERVATION_MODEL_INADEQUATE"


class AdmissionDisposition(StrEnum):
    RESEARCH_ONLY = "RESEARCH_ONLY"
    RIVAL_FAMILY_ONLY = "RIVAL_FAMILY_ONLY"
    ADMITTED_COMPONENT = "ADMITTED_COMPONENT"
    F7_CANDIDATE = "F7_CANDIDATE"
    F7_ADMITTED = "F7_ADMITTED"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    UNIDENTIFIABLE_WITH_CURRENT_EVIDENCE = "UNIDENTIFIABLE_WITH_CURRENT_EVIDENCE"
